// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/user_to_donation.proto

package user_donation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// for username
type DetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DetailReq) Reset() {
	*x = DetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_to_donation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailReq) ProtoMessage() {}

func (x *DetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_to_donation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailReq.ProtoReflect.Descriptor instead.
func (*DetailReq) Descriptor() ([]byte, []int) {
	return file_proto_user_to_donation_proto_rawDescGZIP(), []int{0}
}

func (x *DetailReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UsernameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *UsernameResp) Reset() {
	*x = UsernameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_to_donation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsernameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameResp) ProtoMessage() {}

func (x *UsernameResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_to_donation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameResp.ProtoReflect.Descriptor instead.
func (*UsernameResp) Descriptor() ([]byte, []int) {
	return file_proto_user_to_donation_proto_rawDescGZIP(), []int{1}
}

func (x *UsernameResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_proto_user_to_donation_proto protoreflect.FileDescriptor

var file_proto_user_to_donation_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f,
	0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x24, 0x0a, 0x09, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0c, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x42, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x13, 0x5a, 0x11, 0x2f, 0x70,
	0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_to_donation_proto_rawDescOnce sync.Once
	file_proto_user_to_donation_proto_rawDescData = file_proto_user_to_donation_proto_rawDesc
)

func file_proto_user_to_donation_proto_rawDescGZIP() []byte {
	file_proto_user_to_donation_proto_rawDescOnce.Do(func() {
		file_proto_user_to_donation_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_to_donation_proto_rawDescData)
	})
	return file_proto_user_to_donation_proto_rawDescData
}

var file_proto_user_to_donation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_to_donation_proto_goTypes = []any{
	(*DetailReq)(nil),    // 0: user.DetailReq
	(*UsernameResp)(nil), // 1: user.UsernameResp
}
var file_proto_user_to_donation_proto_depIdxs = []int32{
	0, // 0: user.UserDonation.GetUsername:input_type -> user.DetailReq
	1, // 1: user.UserDonation.GetUsername:output_type -> user.UsernameResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_to_donation_proto_init() }
func file_proto_user_to_donation_proto_init() {
	if File_proto_user_to_donation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_to_donation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_to_donation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UsernameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_to_donation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_to_donation_proto_goTypes,
		DependencyIndexes: file_proto_user_to_donation_proto_depIdxs,
		MessageInfos:      file_proto_user_to_donation_proto_msgTypes,
	}.Build()
	File_proto_user_to_donation_proto = out.File
	file_proto_user_to_donation_proto_rawDesc = nil
	file_proto_user_to_donation_proto_goTypes = nil
	file_proto_user_to_donation_proto_depIdxs = nil
}
