// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: proto/donation_to_rest.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Donation_GetAllDonations_FullMethodName   = "/donation.Donation/GetAllDonations"
	Donation_GetDonationDetail_FullMethodName = "/donation.Donation/GetDonationDetail"
	Donation_CreateDonation_FullMethodName    = "/donation.Donation/CreateDonation"
	Donation_EditDonation_FullMethodName      = "/donation.Donation/EditDonation"
	Donation_DeleteDonation_FullMethodName    = "/donation.Donation/DeleteDonation"
)

// DonationClient is the client API for Donation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DonationClient interface {
	GetAllDonations(ctx context.Context, in *DonationReq, opts ...grpc.CallOption) (*DonationList, error)
	GetDonationDetail(ctx context.Context, in *DonationDetailReq, opts ...grpc.CallOption) (*DonationDetailResp, error)
	CreateDonation(ctx context.Context, in *CreateDonationReq, opts ...grpc.CallOption) (*CreateResp, error)
	EditDonation(ctx context.Context, in *EditDonationReq, opts ...grpc.CallOption) (*EditResp, error)
	DeleteDonation(ctx context.Context, in *DeleteDonationReq, opts ...grpc.CallOption) (*DeleteResp, error)
}

type donationClient struct {
	cc grpc.ClientConnInterface
}

func NewDonationClient(cc grpc.ClientConnInterface) DonationClient {
	return &donationClient{cc}
}

func (c *donationClient) GetAllDonations(ctx context.Context, in *DonationReq, opts ...grpc.CallOption) (*DonationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DonationList)
	err := c.cc.Invoke(ctx, Donation_GetAllDonations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donationClient) GetDonationDetail(ctx context.Context, in *DonationDetailReq, opts ...grpc.CallOption) (*DonationDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DonationDetailResp)
	err := c.cc.Invoke(ctx, Donation_GetDonationDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donationClient) CreateDonation(ctx context.Context, in *CreateDonationReq, opts ...grpc.CallOption) (*CreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, Donation_CreateDonation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donationClient) EditDonation(ctx context.Context, in *EditDonationReq, opts ...grpc.CallOption) (*EditResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditResp)
	err := c.cc.Invoke(ctx, Donation_EditDonation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donationClient) DeleteDonation(ctx context.Context, in *DeleteDonationReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, Donation_DeleteDonation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DonationServer is the server API for Donation service.
// All implementations should embed UnimplementedDonationServer
// for forward compatibility
type DonationServer interface {
	GetAllDonations(context.Context, *DonationReq) (*DonationList, error)
	GetDonationDetail(context.Context, *DonationDetailReq) (*DonationDetailResp, error)
	CreateDonation(context.Context, *CreateDonationReq) (*CreateResp, error)
	EditDonation(context.Context, *EditDonationReq) (*EditResp, error)
	DeleteDonation(context.Context, *DeleteDonationReq) (*DeleteResp, error)
}

// UnimplementedDonationServer should be embedded to have forward compatible implementations.
type UnimplementedDonationServer struct {
}

func (UnimplementedDonationServer) GetAllDonations(context.Context, *DonationReq) (*DonationList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDonations not implemented")
}
func (UnimplementedDonationServer) GetDonationDetail(context.Context, *DonationDetailReq) (*DonationDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDonationDetail not implemented")
}
func (UnimplementedDonationServer) CreateDonation(context.Context, *CreateDonationReq) (*CreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDonation not implemented")
}
func (UnimplementedDonationServer) EditDonation(context.Context, *EditDonationReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditDonation not implemented")
}
func (UnimplementedDonationServer) DeleteDonation(context.Context, *DeleteDonationReq) (*DeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDonation not implemented")
}

// UnsafeDonationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DonationServer will
// result in compilation errors.
type UnsafeDonationServer interface {
	mustEmbedUnimplementedDonationServer()
}

func RegisterDonationServer(s grpc.ServiceRegistrar, srv DonationServer) {
	s.RegisterService(&Donation_ServiceDesc, srv)
}

func _Donation_GetAllDonations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DonationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonationServer).GetAllDonations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Donation_GetAllDonations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonationServer).GetAllDonations(ctx, req.(*DonationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Donation_GetDonationDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DonationDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonationServer).GetDonationDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Donation_GetDonationDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonationServer).GetDonationDetail(ctx, req.(*DonationDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Donation_CreateDonation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDonationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonationServer).CreateDonation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Donation_CreateDonation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonationServer).CreateDonation(ctx, req.(*CreateDonationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Donation_EditDonation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDonationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonationServer).EditDonation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Donation_EditDonation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonationServer).EditDonation(ctx, req.(*EditDonationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Donation_DeleteDonation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDonationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonationServer).DeleteDonation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Donation_DeleteDonation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonationServer).DeleteDonation(ctx, req.(*DeleteDonationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Donation_ServiceDesc is the grpc.ServiceDesc for Donation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Donation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donation.Donation",
	HandlerType: (*DonationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllDonations",
			Handler:    _Donation_GetAllDonations_Handler,
		},
		{
			MethodName: "GetDonationDetail",
			Handler:    _Donation_GetDonationDetail_Handler,
		},
		{
			MethodName: "CreateDonation",
			Handler:    _Donation_CreateDonation_Handler,
		},
		{
			MethodName: "EditDonation",
			Handler:    _Donation_EditDonation_Handler,
		},
		{
			MethodName: "DeleteDonation",
			Handler:    _Donation_DeleteDonation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/donation_to_rest.proto",
}
