// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/donation_registry.proto

package pbDonationRegistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DonationReg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DonationId string `protobuf:"bytes,1,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
}

func (x *DonationReg) Reset() {
	*x = DonationReg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_donation_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonationReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationReg) ProtoMessage() {}

func (x *DonationReg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationReg.ProtoReflect.Descriptor instead.
func (*DonationReg) Descriptor() ([]byte, []int) {
	return file_proto_donation_registry_proto_rawDescGZIP(), []int{0}
}

func (x *DonationReg) GetDonationId() string {
	if x != nil {
		return x.DonationId
	}
	return ""
}

type DonationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDonationExist bool    `protobuf:"varint,1,opt,name=is_donation_exist,json=isDonationExist,proto3" json:"is_donation_exist,omitempty"`
	DonationName    string  `protobuf:"bytes,2,opt,name=donation_name,json=donationName,proto3" json:"donation_name,omitempty"`
	Description     string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AmountToPay     float64 `protobuf:"fixed64,4,opt,name=amount_to_pay,json=amountToPay,proto3" json:"amount_to_pay,omitempty"`
	RecipientId     uint64  `protobuf:"varint,5,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	RecipientName   string  `protobuf:"bytes,6,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
}

func (x *DonationResp) Reset() {
	*x = DonationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_donation_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationResp) ProtoMessage() {}

func (x *DonationResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationResp.ProtoReflect.Descriptor instead.
func (*DonationResp) Descriptor() ([]byte, []int) {
	return file_proto_donation_registry_proto_rawDescGZIP(), []int{1}
}

func (x *DonationResp) GetIsDonationExist() bool {
	if x != nil {
		return x.IsDonationExist
	}
	return false
}

func (x *DonationResp) GetDonationName() string {
	if x != nil {
		return x.DonationName
	}
	return ""
}

func (x *DonationResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DonationResp) GetAmountToPay() float64 {
	if x != nil {
		return x.AmountToPay
	}
	return 0
}

func (x *DonationResp) GetRecipientId() uint64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *DonationResp) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

var File_proto_donation_registry_proto protoreflect.FileDescriptor

var file_proto_donation_registry_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x0b, 0x44, 0x6f, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xef, 0x01, 0x0a, 0x0c, 0x44, 0x6f,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73,
	0x5f, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64,
	0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x50, 0x61,
	0x79, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x54, 0x0a, 0x10, 0x44,
	0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12,
	0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x15, 0x2e, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x6f,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x1a, 0x16, 0x2e, 0x64, 0x6f, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x44, 0x6f, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_donation_registry_proto_rawDescOnce sync.Once
	file_proto_donation_registry_proto_rawDescData = file_proto_donation_registry_proto_rawDesc
)

func file_proto_donation_registry_proto_rawDescGZIP() []byte {
	file_proto_donation_registry_proto_rawDescOnce.Do(func() {
		file_proto_donation_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_donation_registry_proto_rawDescData)
	})
	return file_proto_donation_registry_proto_rawDescData
}

var file_proto_donation_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_donation_registry_proto_goTypes = []any{
	(*DonationReg)(nil),  // 0: donation.DonationReg
	(*DonationResp)(nil), // 1: donation.DonationResp
}
var file_proto_donation_registry_proto_depIdxs = []int32{
	0, // 0: donation.DonationRegistry.GetDonationData:input_type -> donation.DonationReg
	1, // 1: donation.DonationRegistry.GetDonationData:output_type -> donation.DonationResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_donation_registry_proto_init() }
func file_proto_donation_registry_proto_init() {
	if File_proto_donation_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_donation_registry_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DonationReg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_donation_registry_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DonationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_donation_registry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_donation_registry_proto_goTypes,
		DependencyIndexes: file_proto_donation_registry_proto_depIdxs,
		MessageInfos:      file_proto_donation_registry_proto_msgTypes,
	}.Build()
	File_proto_donation_registry_proto = out.File
	file_proto_donation_registry_proto_rawDesc = nil
	file_proto_donation_registry_proto_goTypes = nil
	file_proto_donation_registry_proto_depIdxs = nil
}
