// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: proto/donation_registry.proto

package pbDonationRegistry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DonationRegistry_GetDonationData_FullMethodName = "/donation.DonationRegistry/GetDonationData"
)

// DonationRegistryClient is the client API for DonationRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DonationRegistryClient interface {
	GetDonationData(ctx context.Context, in *DonationReq, opts ...grpc.CallOption) (*DonationResp, error)
}

type donationRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewDonationRegistryClient(cc grpc.ClientConnInterface) DonationRegistryClient {
	return &donationRegistryClient{cc}
}

func (c *donationRegistryClient) GetDonationData(ctx context.Context, in *DonationReq, opts ...grpc.CallOption) (*DonationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DonationResp)
	err := c.cc.Invoke(ctx, DonationRegistry_GetDonationData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DonationRegistryServer is the server API for DonationRegistry service.
// All implementations should embed UnimplementedDonationRegistryServer
// for forward compatibility
type DonationRegistryServer interface {
	GetDonationData(context.Context, *DonationReq) (*DonationResp, error)
}

// UnimplementedDonationRegistryServer should be embedded to have forward compatible implementations.
type UnimplementedDonationRegistryServer struct {
}

func (UnimplementedDonationRegistryServer) GetDonationData(context.Context, *DonationReq) (*DonationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDonationData not implemented")
}

// UnsafeDonationRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DonationRegistryServer will
// result in compilation errors.
type UnsafeDonationRegistryServer interface {
	mustEmbedUnimplementedDonationRegistryServer()
}

func RegisterDonationRegistryServer(s grpc.ServiceRegistrar, srv DonationRegistryServer) {
	s.RegisterService(&DonationRegistry_ServiceDesc, srv)
}

func _DonationRegistry_GetDonationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DonationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonationRegistryServer).GetDonationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonationRegistry_GetDonationData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonationRegistryServer).GetDonationData(ctx, req.(*DonationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DonationRegistry_ServiceDesc is the grpc.ServiceDesc for DonationRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DonationRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donation.DonationRegistry",
	HandlerType: (*DonationRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDonationData",
			Handler:    _DonationRegistry_GetDonationData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/donation_registry.proto",
}
