// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: proto/registry_rest.proto

package pbRegistryRest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RegistryRest_GetAllRegistries_FullMethodName = "/registry.RegistryRest/GetAllRegistries"
	RegistryRest_GetRegistryID_FullMethodName    = "/registry.RegistryRest/GetRegistryID"
	RegistryRest_Donate_FullMethodName           = "/registry.RegistryRest/Donate"
	RegistryRest_DeleteRegistry_FullMethodName   = "/registry.RegistryRest/DeleteRegistry"
)

// RegistryRestClient is the client API for RegistryRest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryRestClient interface {
	GetAllRegistries(ctx context.Context, in *AllReq, opts ...grpc.CallOption) (*RegistriesResp, error)
	GetRegistryID(ctx context.Context, in *GetRegistryReq, opts ...grpc.CallOption) (*RegistryResp, error)
	Donate(ctx context.Context, in *DonationReq, opts ...grpc.CallOption) (*DonateResp, error)
	DeleteRegistry(ctx context.Context, in *DeleteRegistryReq, opts ...grpc.CallOption) (*DeleteResp, error)
}

type registryRestClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryRestClient(cc grpc.ClientConnInterface) RegistryRestClient {
	return &registryRestClient{cc}
}

func (c *registryRestClient) GetAllRegistries(ctx context.Context, in *AllReq, opts ...grpc.CallOption) (*RegistriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistriesResp)
	err := c.cc.Invoke(ctx, RegistryRest_GetAllRegistries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryRestClient) GetRegistryID(ctx context.Context, in *GetRegistryReq, opts ...grpc.CallOption) (*RegistryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResp)
	err := c.cc.Invoke(ctx, RegistryRest_GetRegistryID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryRestClient) Donate(ctx context.Context, in *DonationReq, opts ...grpc.CallOption) (*DonateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DonateResp)
	err := c.cc.Invoke(ctx, RegistryRest_Donate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryRestClient) DeleteRegistry(ctx context.Context, in *DeleteRegistryReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, RegistryRest_DeleteRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryRestServer is the server API for RegistryRest service.
// All implementations should embed UnimplementedRegistryRestServer
// for forward compatibility
type RegistryRestServer interface {
	GetAllRegistries(context.Context, *AllReq) (*RegistriesResp, error)
	GetRegistryID(context.Context, *GetRegistryReq) (*RegistryResp, error)
	Donate(context.Context, *DonationReq) (*DonateResp, error)
	DeleteRegistry(context.Context, *DeleteRegistryReq) (*DeleteResp, error)
}

// UnimplementedRegistryRestServer should be embedded to have forward compatible implementations.
type UnimplementedRegistryRestServer struct {
}

func (UnimplementedRegistryRestServer) GetAllRegistries(context.Context, *AllReq) (*RegistriesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRegistries not implemented")
}
func (UnimplementedRegistryRestServer) GetRegistryID(context.Context, *GetRegistryReq) (*RegistryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegistryID not implemented")
}
func (UnimplementedRegistryRestServer) Donate(context.Context, *DonationReq) (*DonateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Donate not implemented")
}
func (UnimplementedRegistryRestServer) DeleteRegistry(context.Context, *DeleteRegistryReq) (*DeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRegistry not implemented")
}

// UnsafeRegistryRestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryRestServer will
// result in compilation errors.
type UnsafeRegistryRestServer interface {
	mustEmbedUnimplementedRegistryRestServer()
}

func RegisterRegistryRestServer(s grpc.ServiceRegistrar, srv RegistryRestServer) {
	s.RegisterService(&RegistryRest_ServiceDesc, srv)
}

func _RegistryRest_GetAllRegistries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryRestServer).GetAllRegistries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryRest_GetAllRegistries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryRestServer).GetAllRegistries(ctx, req.(*AllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryRest_GetRegistryID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryRestServer).GetRegistryID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryRest_GetRegistryID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryRestServer).GetRegistryID(ctx, req.(*GetRegistryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryRest_Donate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DonationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryRestServer).Donate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryRest_Donate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryRestServer).Donate(ctx, req.(*DonationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryRest_DeleteRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRegistryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryRestServer).DeleteRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryRest_DeleteRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryRestServer).DeleteRegistry(ctx, req.(*DeleteRegistryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryRest_ServiceDesc is the grpc.ServiceDesc for RegistryRest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryRest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.RegistryRest",
	HandlerType: (*RegistryRestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllRegistries",
			Handler:    _RegistryRest_GetAllRegistries_Handler,
		},
		{
			MethodName: "GetRegistryID",
			Handler:    _RegistryRest_GetRegistryID_Handler,
		},
		{
			MethodName: "Donate",
			Handler:    _RegistryRest_Donate_Handler,
		},
		{
			MethodName: "DeleteRegistry",
			Handler:    _RegistryRest_DeleteRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/registry_rest.proto",
}
